### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by cooperpellaton** [yoshuawuyts/dotfiles#41]
I tried to install your dotfiles to grab the tmux theme but I can't build the files. I checked in the working directory and don't see a makefile, thus when I run `make` I get this in return `make: *** No targets specified and no makefile found.  Stop.`

Not sure where to go from here.

**Comment by yoshuawuyts** [comment]
hah, well I removed the Makefile from the repo. If you clone the repo, running `scripts/setup` and `scripts/tmux` should get you there. Cheers!
