### ISSUE TITLE
Curious about your tmux windows

### ISSUE THREAD

**Issue by liaa** [yoshuawuyts/dotfiles#46]
By checking the code from `bin/mx` I notice that you have several tmux window that is always there.

I am so curious the way you use the following windows. Can you elaborate on them, thanks.

* knowledge
* templates
* notes

**Comment by yoshuawuyts** [comment]
- knowledge is notes https://github.com/yoshuawuyts/knowledge/
- templates is stuff I use to generate files https://github.com/yoshuawuyts/templates
- notes is private notes

They're all bound to windows, so regardless of the project I'm working on, I can access these files. Check out the bottom left of my screen:

<img width="1280" alt="screen shot 2017-07-01 at 14 29 02" src="https://user-images.githubusercontent.com/2467194/27762060-da24cb98-5e69-11e7-8435-df67b72953b0.png">
